style proof
style proofIsDone
style proofIsIncomplete
style proofIsPending
style rules
style inference
style tagBox
style tag
style sibling
style junct
style viewport
style commaList
style relMark
style offsetBox
style working
style page
style errorStyle
style turnstile
style centerTable
style offsetInner
style green
style primaryConnective
style primaryExpr
